app:
  bot: # line bot setup
    port: 5000
    channel_access_token: ""
    channel_secret: ""
  command: # bot commmand
    help:
      message: |
        使用說明
        /help: 使用說明
        /stat [開始日期] [結束日期]: 統計數據
        /gpt: 聊天機器人
        /chance (事項1 事項2 事項3...)
        /dice
        /fortune (事項1 事項2 事項3...)
        /pick [選項1] (選項2 選項3...)
        /echo
          ls
          add [input] [output]
          rm [input1] (input2...)
          reset
    gpt:
      temperature: [0.8, 1.2] # number or [min, max]

# module: chatgpt
chatgpt: 
  token: ""
  max_tokens: 1000

# module: games
games:
  chance: [0.2, 0.8]
  fortune:
    key: ["大吉", "吉", "小吉", "尚可", "小兇", "兇", "大凶"]
    sep: [0, 0.05, 0.15, 0.35, 0.65, 0.85, 0.95, 1]
